	@echo "Makefile targets:"
	@echo "  install        - install dependencies via uv / pip"
	@echo "  test-no-ai     - run no_ai deterministic suite with self-healing and classification"
	@echo "  test-ai        - run ai-assisted self-healing branch suite"
	@echo "  test-stagehand - run declarative stagehand agent suite"
	@echo "  test-all       - run all execution branches sequentially"
	@echo "  clear          - clean reports, screenshots, videos, logs"
